include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    uri_does_not_exist: ignore
    undefined_identifier: ignore
    undefined_class: ignore
    undefined_method: ignore
    creation_with_non_type: ignore
    override_on_non_overriding_member: ignore
    unused_import: ignore
